### ISSUE TITLE
CI integration

### ISSUE THREAD

**Issue by mkae** [neverpanic/macports-ports#1]
Hi Clemens,

how will the CI system (involving MacPorts' builders) be integrated in the future once the move to GitHub has happened.

Do you think about automated CI also for PRs?

Greets,
Marko

**Comment by neverpanic** [comment]
Hi Marko,

please note that this repository is a demo repository and will not be the final one to be used by the macports organization on GitHub. Additionally, we will not use GitHub issues, so it's not really useful to open tickets here.

To answer your question:

- for the existing CI system, we expect it to continue working as-is with changed sources and trigger on push, rather than commit (obviously). Ryan will set up the Git repositories but disable push access and automatically update those repositories after SVN commits. We'll use this read-only copy to switch the buildbot configuration over. Since buildbot already supports Git very well, this is a matter of changing a few lines of configuration.
- for pull requests we have discussed CI support, but not started implementing or finished anything, because we wanted to improve incrementally rather than solving all problems at once. In theory, our new mp-buildbot tooling gives us everything we need to do automatic validation of new ports, but we haven't discussed the requirements to make this safe (I expect that we'd have to use snapshots of VMs that we start for each build, so that whatever a Portfile in a pull request does does not affect our production infrastructure).

**Comment by mkae** [comment]
I am aware of that this is not an official repository. :)

Looking forward to the transition. PRs should make port maintenance so much easier for those who contribute and those who review.

Thanks for the information. I guess I should have directed this to the ML instead...
